// ─────────────────────────────────────────────────────────
// In-memory data store — replaces Supabase until connected
// Mirrors the exact database schema from migration 001
// ─────────────────────────────────────────────────────────

import { v4 as uuidv4 } from 'uuid';

// ── Seed data matching supabase/seed.sql ────────────────

const categoryIds = {
  tshirts: uuidv4(),
  hoodies: uuidv4(),
  sweatshirts: uuidv4(),
  caps: uuidv4(),
  accessories: uuidv4(),
};

const collectionIds = {
  summer: uuidv4(),
  streetwear: uuidv4(),
  custom: uuidv4(),
  bestSellers: uuidv4(),
};

const productIds = {
  classicTee: uuidv4(),
  graphicTee: uuidv4(),
  hoodie: uuidv4(),
};

function generateVariants(
  productId: string,
  prefix: string,
  sizes: string[],
  colors: Array<{ code: string; name: string; hex: string }>,
  price: number,
  stock: number,
) {
  const variants: any[] = [];
  for (const size of sizes) {
    for (const color of colors) {
      variants.push({
        id: uuidv4(),
        product_id: productId,
        sku: `${prefix}-${size}-${color.code}`,
        size,
        color: color.name,
        color_hex: color.hex,
        price,
        stock_quantity: stock,
        reserved_quantity: 0,
        is_active: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      });
    }
  }
  return variants;
}

const teeVariants = generateVariants(
  productIds.classicTee,
  'COT',
  ['S', 'M', 'L', 'XL', 'XXL'],
  [
    { code: 'BLK', name: 'Black', hex: '#111111' },
    { code: 'WHT', name: 'White', hex: '#FFFFFF' },
    { code: 'SNS', name: 'Sandstone', hex: '#D4C4A8' },
  ],
  1299,
  25,
);

const graphicVariants = generateVariants(
  productIds.graphicTee,
  'GPT',
  ['S', 'M', 'L', 'XL'],
  [{ code: 'BLK', name: 'Black', hex: '#111111' }],
  1499,
  15,
);

const hoodieVariants = generateVariants(
  productIds.hoodie,
  'EPH',
  ['S', 'M', 'L', 'XL', 'XXL'],
  [
    { code: 'CHR', name: 'Charcoal', hex: '#333333' },
    { code: 'OAT', name: 'Oatmeal', hex: '#E8DCC8' },
  ],
  2499,
  10,
);

export const db = {
  categories: [
    { id: categoryIds.tshirts, name: 'T-Shirts', slug: 't-shirts', parent_id: null, image_key: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: categoryIds.hoodies, name: 'Hoodies', slug: 'hoodies', parent_id: null, image_key: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: categoryIds.sweatshirts, name: 'Sweatshirts', slug: 'sweatshirts', parent_id: null, image_key: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: categoryIds.caps, name: 'Caps', slug: 'caps', parent_id: null, image_key: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: categoryIds.accessories, name: 'Accessories', slug: 'accessories', parent_id: null, image_key: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ] as any[],

  collections: [
    { id: collectionIds.summer, name: 'Summer 2025', slug: 'summer-2025', description: 'Fresh summer collection with bold prints and light fabrics.', banner_key: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: collectionIds.streetwear, name: 'Streetwear Essentials', slug: 'streetwear-essentials', description: 'Core streetwear pieces for everyday style.', banner_key: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: collectionIds.custom, name: 'Custom Favourites', slug: 'custom-favourites', description: 'Most popular customizable products.', banner_key: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: collectionIds.bestSellers, name: 'Best Sellers', slug: 'best-sellers', description: 'Our top-selling products.', banner_key: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ] as any[],

  products: [
    {
      id: productIds.classicTee,
      category_id: categoryIds.tshirts,
      title: 'Classic Oversized Tee',
      slug: 'classic-oversized-tee',
      description: 'Premium 220 GSM cotton oversized tee with dropped shoulders. Perfect canvas for custom designs.',
      status: 'active',
      base_price: 1299,
      compare_at_price: 1599,
      customization_enabled: true,
      seo_title: 'Classic Oversized Tee — Bingooo',
      seo_description: 'Premium oversized tee in 220 GSM cotton. Customize with your own design or wear it plain.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: productIds.graphicTee,
      category_id: categoryIds.tshirts,
      title: 'Graphic Print Tee — Midnight',
      slug: 'graphic-print-tee-midnight',
      description: 'Bold midnight-themed graphic print on soft cotton.',
      status: 'active',
      base_price: 1499,
      compare_at_price: null,
      customization_enabled: false,
      seo_title: 'Graphic Print Tee Midnight — Bingooo',
      seo_description: 'Stand out with our midnight graphic print on premium cotton.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: productIds.hoodie,
      category_id: categoryIds.hoodies,
      title: 'Essential Pullover Hoodie',
      slug: 'essential-pullover-hoodie',
      description: 'Cozy 350 GSM fleece-lined hoodie. Adjustable hood, kangaroo pocket, ribbed cuffs.',
      status: 'active',
      base_price: 2499,
      compare_at_price: 2999,
      customization_enabled: true,
      seo_title: 'Essential Pullover Hoodie — Bingooo',
      seo_description: 'Warm and customizable pullover hoodie in premium fleece.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as any[],

  product_images: [
    { id: uuidv4(), product_id: productIds.classicTee, url: '/custom/tshirt-step-1.png', object_key: '/custom/tshirt-step-1.png', alt_text: 'Classic Oversized Tee in Natural Beige', sort_order: 0, is_primary: true },
    { id: uuidv4(), product_id: productIds.graphicTee, url: '/custom/tshirt-step-3-black.png', object_key: '/custom/tshirt-step-3-black.png', alt_text: 'Graphic Print Tee in Midnight Obsidian', sort_order: 0, is_primary: true },
    { id: uuidv4(), product_id: productIds.hoodie, url: '/custom/tshirt-step-2.png', object_key: '/custom/tshirt-step-2.png', alt_text: 'Essential Custom Apparel in Sandstone', sort_order: 0, is_primary: true },
  ] as any[],
  product_variants: [...teeVariants, ...graphicVariants, ...hoodieVariants] as any[],
  product_collections: [
    { product_id: productIds.classicTee, collection_id: collectionIds.streetwear },
    { product_id: productIds.classicTee, collection_id: collectionIds.custom },
    { product_id: productIds.classicTee, collection_id: collectionIds.bestSellers },
    { product_id: productIds.graphicTee, collection_id: collectionIds.summer },
    { product_id: productIds.hoodie, collection_id: collectionIds.streetwear },
    { product_id: productIds.hoodie, collection_id: collectionIds.custom },
  ] as any[],
  users: [
    {
      id: 'usr-admin-1',
      email: 'admin@bingooo.in',
      password_hash: '761a5f614714797131834bd1b84be483:de13a2b9265be7125e297479cf6090001b31044333bbc3b1b9d53234c822557a03916f0262076cd6463d7c964fac37f91825ad326965084a112523802f3c2fbf', // Admin@123456
      full_name: 'Mani P.',
      phone: '+91 98765 43210',
      role: 'SUPER_ADMIN',
      status: 'active',
      avatar_key: null,
      created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'usr-staff-2',
      email: 'siddharth@bingooo.in',
      password_hash: '761a5f614714797131834bd1b84be483:de13a2b9265be7125e297479cf6090001b31044333bbc3b1b9d53234c822557a03916f0262076cd6463d7c964fac37f91825ad326965084a112523802f3c2fbf',
      full_name: 'Siddharth Rao',
      phone: '+91 98111 22334',
      role: 'ORDER_MANAGER',
      status: 'active',
      avatar_key: null,
      created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'usr-staff-3',
      email: 'ananya.d@bingooo.in',
      password_hash: '761a5f614714797131834bd1b84be483:de13a2b9265be7125e297479cf6090001b31044333bbc3b1b9d53234c822557a03916f0262076cd6463d7c964fac37f91825ad326965084a112523802f3c2fbf',
      full_name: 'Ananya Deshmukh',
      phone: '+91 99200 44556',
      role: 'PRODUCT_MANAGER',
      status: 'active',
      avatar_key: null,
      created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'usr-cust-1',
      email: 'customer@bingooo.in',
      password_hash: '46e2c1466283e090b9a838537ea60558:61e9bd6e6aace9b240978a04f8291c53fee14b503297ce34ccad53cbdb07f88063e861cccb6c511d09869d96969e1517afa888721bf65dffcfb98a1274ebfa63', // Customer@123456
      full_name: 'Aditi Sharma',
      phone: '+91 98765 43210',
      role: 'CUSTOMER',
      status: 'active',
      avatar_key: null,
      created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'usr-cust-2',
      email: 'akash.verma@example.com',
      password_hash: '46e2c1466283e090b9a838537ea60558:61e9bd6e6aace9b240978a04f8291c53fee14b503297ce34ccad53cbdb07f88063e861cccb6c511d09869d96969e1517afa888721bf65dffcfb98a1274ebfa63',
      full_name: 'Akash Verma',
      phone: '+91 98222 33445',
      role: 'CUSTOMER',
      status: 'active',
      avatar_key: null,
      created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'usr-cust-3',
      email: 'devika.pillai@outlook.com',
      password_hash: '46e2c1466283e090b9a838537ea60558:61e9bd6e6aace9b240978a04f8291c53fee14b503297ce34ccad53cbdb07f88063e861cccb6c511d09869d96969e1517afa888721bf65dffcfb98a1274ebfa63',
      full_name: 'Devika Pillai',
      phone: '+91 97333 44556',
      role: 'CUSTOMER',
      status: 'active',
      avatar_key: null,
      created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as any[],

  roles: [
    {
      id: 'role-super-admin',
      name: 'Super Admin',
      code: 'SUPER_ADMIN',
      description: 'Full unrestricted system and database access.',
      is_system: true,
      permissions: ['*'],
    },
    {
      id: 'role-admin',
      name: 'Admin',
      code: 'ADMIN',
      description: 'Comprehensive store management excluding master server environment configurations.',
      is_system: true,
      permissions: [
        'products.read', 'products.create', 'products.update', 'products.delete',
        'orders.read', 'orders.update',
        'customizations.review',
        'payments.read', 'refunds.manage',
        'inventory.read', 'inventory.update',
        'reviews.manage', 'banners.manage', 'coupons.manage',
      ],
    },
    {
      id: 'role-order-manager',
      name: 'Order Manager',
      code: 'ORDER_MANAGER',
      description: 'Handle order verification, fulfillment status, and logistics dispatch.',
      is_system: false,
      permissions: ['orders.read', 'orders.update', 'customizations.review', 'payments.read'],
    },
    {
      id: 'role-product-manager',
      name: 'Product Manager',
      code: 'PRODUCT_MANAGER',
      description: 'Manage catalog, garments, descriptions, inventory, and banner campaigns.',
      is_system: false,
      permissions: ['products.read', 'products.create', 'products.update', 'inventory.read', 'inventory.update', 'banners.manage'],
    },
    {
      id: 'role-support',
      name: 'Customer Support',
      code: 'SUPPORT',
      description: 'Assist customers with orders, returns, and reviews.',
      is_system: false,
      permissions: ['orders.read', 'reviews.manage', 'returns.manage'],
    },
    {
      id: 'role-customer',
      name: 'Customer',
      code: 'CUSTOMER',
      description: 'End customer permissions for shopping, orders, reviews, and customization.',
      is_system: true,
      permissions: ['orders.own', 'profile.own', 'reviews.create', 'customizations.create'],
    },
  ] as any[],

  permissions: [
    { key: 'products.read', label: 'View Products & Catalog', group: 'Products' },
    { key: 'products.create', label: 'Create New Garments', group: 'Products' },
    { key: 'products.update', label: 'Update Pricing & Specs', group: 'Products' },
    { key: 'products.delete', label: 'Archive / Delete Garments', group: 'Products' },
    { key: 'orders.read', label: 'View Customer Orders', group: 'Orders' },
    { key: 'orders.update', label: 'Update Fulfillment & Status', group: 'Orders' },
    { key: 'customizations.review', label: 'Review Custom Artwork', group: 'Custom Studio' },
    { key: 'payments.read', label: 'View Payment Ledgers', group: 'Finance' },
    { key: 'refunds.manage', label: 'Issue & Authorize Refunds', group: 'Finance' },
    { key: 'users.manage', label: 'Manage Staff Members', group: 'Team' },
    { key: 'roles.manage', label: 'Modify Permissions Matrix', group: 'Team' },
    { key: 'settings.manage', label: 'Configure Store Parameters', group: 'Settings' },
  ] as any[],

  inventory_movements: [] as any[],
  wishlists: [
    { id: uuidv4(), user_id: 'usr-cust-1', product_id: productIds.hoodie, created_at: new Date().toISOString() },
  ] as any[],
  carts: [] as any[],
  cart_items: [] as any[],

  orders: [
    {
      id: 'ord-1029',
      order_number: 'BING-89421',
      user_id: 'usr-cust-2',
      status: 'processing',
      payment_status: 'paid',
      payment_method: 'prepaid',
      currency: 'INR',
      subtotal: 2398,
      discount: 0,
      shipping_fee: 0,
      tax: 100,
      total: 2498,
      coupon_code: null,
      cod_deposit: null,
      notes: 'Customer requested double packaging',
      shipping_address: {
        name: 'Akash Verma',
        phone: '9822233445',
        line1: '402, Lotus Grandeur, Veera Desai Road',
        line2: 'Andheri West',
        city: 'Mumbai',
        state: 'Maharashtra',
        postal_code: '400053',
        country: 'IN',
      },
      tracking_number: 'BLUEDART-88219412',
      carrier: 'BlueDart',
      created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
      updated_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    },
    {
      id: 'ord-1028',
      order_number: 'BING-89419',
      user_id: 'usr-cust-3',
      status: 'shipped',
      payment_status: 'paid',
      payment_method: 'prepaid',
      currency: 'INR',
      subtotal: 1299,
      discount: 200,
      shipping_fee: 100,
      tax: 0,
      total: 1199,
      coupon_code: 'FLAT200',
      cod_deposit: null,
      notes: null,
      shipping_address: {
        name: 'Devika Pillai',
        phone: '9733344556',
        line1: 'House #12, Palm Grove Enclave',
        line2: 'Panampilly Nagar',
        city: 'Kochi',
        state: 'Kerala',
        postal_code: '682036',
        country: 'IN',
      },
      tracking_number: 'DELHIVERY-99210419',
      carrier: 'Delhivery',
      created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
      updated_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    },
    {
      id: 'ord-1027',
      order_number: 'BING-89412',
      user_id: 'usr-cust-1',
      status: 'delivered',
      payment_status: 'paid',
      payment_method: 'prepaid',
      currency: 'INR',
      subtotal: 3499,
      discount: 0,
      shipping_fee: 0,
      tax: 0,
      total: 3499,
      coupon_code: null,
      cod_deposit: null,
      notes: null,
      shipping_address: {
        name: 'Aditi Sharma',
        phone: '9876543210',
        line1: '124, Indiranagar 100ft Road',
        line2: 'Flat 4B, Silicon Heights',
        city: 'Bengaluru',
        state: 'Karnataka',
        postal_code: '560038',
        country: 'IN',
      },
      tracking_number: 'BLUEDART-88219001',
      carrier: 'BlueDart',
      created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      updated_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    },
  ] as any[],

  order_items: [
    {
      id: uuidv4(),
      order_id: 'ord-1029',
      variant_id: teeVariants[0].id,
      product_id: productIds.classicTee,
      customization_id: null,
      quantity: 2,
      unit_price: 1199,
      total_price: 2398,
      title_snapshot: 'Classic Oversized Heavyweight Tee',
      variant_snapshot_json: { size: 'M', color: 'Black', sku: 'COT-M-BLK' },
      created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
    {
      id: uuidv4(),
      order_id: 'ord-1028',
      variant_id: graphicVariants[0].id,
      product_id: productIds.graphicTee,
      customization_id: null,
      quantity: 1,
      unit_price: 1499,
      total_price: 1499,
      title_snapshot: 'Graphic Print Heavyweight Tee',
      variant_snapshot_json: { size: 'L', color: 'Black', sku: 'GPT-L-BLK' },
      created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    },
    {
      id: uuidv4(),
      order_id: 'ord-1027',
      variant_id: hoodieVariants[0].id,
      product_id: productIds.hoodie,
      customization_id: null,
      quantity: 1,
      unit_price: 2499,
      total_price: 2499,
      title_snapshot: 'Essential Pullover Hoodie',
      variant_snapshot_json: { size: 'XL', color: 'Charcoal', sku: 'EPH-XL-CHR' },
      created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
  ] as any[],

  payments: [
    {
      id: 'pay-901',
      order_id: 'ord-1029',
      provider: 'razorpay',
      provider_order_id: 'order_Nz82Lk19J0asQ2',
      provider_payment_id: 'pay_Nz82Lk19J0asQ2',
      status: 'paid',
      amount: 2498,
      currency: 'INR',
      method: 'Razorpay UPI (Google Pay)',
      raw_event_id: null,
      idempotency_key: uuidv4(),
      customer_name: 'Akash Verma',
      customer_email: 'akash.verma@example.com',
      order_number: 'BING-89421',
      created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
      updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
    {
      id: 'pay-902',
      order_id: 'ord-1028',
      provider: 'razorpay',
      provider_order_id: 'order_Nz75Kl02Aa34W1',
      provider_payment_id: 'pay_Nz75Kl02Aa34W1',
      status: 'paid',
      amount: 1199,
      currency: 'INR',
      method: 'HDFC Credit Card (Visa)',
      raw_event_id: null,
      idempotency_key: uuidv4(),
      customer_name: 'Devika Pillai',
      customer_email: 'devika.pillai@outlook.com',
      order_number: 'BING-89419',
      created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
      updated_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    },
    {
      id: 'pay-903',
      order_id: 'ord-1027',
      provider: 'razorpay',
      provider_order_id: 'order_Nz61Mn99Zq00P9',
      provider_payment_id: 'pay_Nz61Mn99Zq00P9',
      status: 'paid',
      amount: 3499,
      currency: 'INR',
      method: 'ICICI NetBanking',
      raw_event_id: null,
      idempotency_key: uuidv4(),
      customer_name: 'Aditi Sharma',
      customer_email: 'customer@bingooo.in',
      order_number: 'BING-89412',
      created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
  ] as any[],

  refunds: [] as any[],

  returns: [
    {
      id: 'ret-101',
      order_id: 'ord-1027',
      order_number: 'BING-89412',
      user_id: 'usr-cust-1',
      customer_name: 'Aditi Sharma',
      customer_phone: '+91 98765 43210',
      garment_title: 'Classic Oversized Heavyweight Tee',
      size: 'XL',
      reason: 'size_fit',
      comments: 'Need size L instead. The oversized boxy cut is larger than expected.',
      refund_amount: 1299,
      status: 'reviewing',
      created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'ret-102',
      order_id: 'ord-1029',
      order_number: 'BING-89421',
      user_id: 'usr-cust-2',
      customer_name: 'Akash Verma',
      customer_phone: '+91 98222 33445',
      garment_title: 'Essential Pullover Hoodie - Charcoal',
      size: 'M',
      reason: 'print_defect',
      comments: 'Custom studio backprint has a slight smudge on the bottom left corner.',
      refund_amount: 2499,
      status: 'pickup_scheduled',
      created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as any[],

  coupons: [
    { id: uuidv4(), code: 'WELCOME10', type: 'percentage', value: 10, min_order_value: 500, max_discount: 200, usage_limit: 100, usage_count: 5, starts_at: null, ends_at: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uuidv4(), code: 'FLAT200', type: 'fixed', value: 200, min_order_value: 1000, max_discount: null, usage_limit: 50, usage_count: 12, starts_at: null, ends_at: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: uuidv4(), code: 'STREETWEAR25', type: 'percentage', value: 25, min_order_value: 1999, max_discount: 750, usage_limit: 200, usage_count: 18, starts_at: null, ends_at: null, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  ] as any[],

  coupon_redemptions: [] as any[],

  custom_requirements: [
    {
      id: 'cr-101',
      customerName: 'Karthik Raman',
      customerEmail: 'karthik.r@techcorp.in',
      customerPhone: '+91 99001 22334',
      garmentType: 'Heavyweight Boxy Tees (240 GSM)',
      quantity: 50,
      printPlacements: ['Front Left Chest (Embroidery)', 'Full Back (Screen Print)'],
      targetDate: '2026-09-25',
      estimatedBudget: 45000,
      status: 'new',
      description: 'Corporate tech hackathon team t-shirts. Need premium charcoal fabric with high density puff print on back.',
      attachmentName: 'TechCorp_Hackathon_Vectors.pdf',
      attachmentUrl: '/sample-vector.pdf',
      internalNotes: 'Contacted vendor for high-density puff ink sample.',
      created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'cr-102',
      customerName: 'Samir Sheikh',
      customerEmail: 'samir.sheikh@musiccollective.com',
      customerPhone: '+91 98200 55443',
      garmentType: 'Oversized Zip Hoodies (380 GSM Fleece)',
      quantity: 30,
      printPlacements: ['Oversized Back Graphic (DTG)', 'Sleeve Tag Print'],
      targetDate: '2026-10-02',
      estimatedBudget: 60000,
      status: 'reviewing',
      description: 'Band merch for nationwide tour drop. Double-layered hood, custom silver metal zip pulls if possible.',
      attachmentName: 'Album_Tour_Artwork_HiRes.ai',
      attachmentUrl: '/sample-vector.ai',
      internalNotes: 'Sample garment sent to client for fit check.',
      created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'cr-103',
      customerName: 'Arjun Nambiar',
      customerEmail: 'arjun@crossfitarena.in',
      customerPhone: '+91 97400 88991',
      garmentType: 'Drop Cut Gym Tanks & Boxy Tees',
      quantity: 100,
      printPlacements: ['Center Chest Vinyl Heat Transfer'],
      targetDate: '2026-09-18',
      estimatedBudget: 75000,
      status: 'approved',
      description: 'Annual championship fitness drop. Sweat-wicking combed cotton blend with reflective logo.',
      attachmentName: 'CrossFit_Championship_Branding.svg',
      attachmentUrl: '/sample-vector.svg',
      internalNotes: 'Quote accepted at Rs. 750/unit. Awaiting advance payment link.',
      created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as any[],

  reviews: [
    {
      id: 'rev-1',
      product_id: productIds.classicTee,
      user_id: 'usr-cust-2',
      customer_name: 'Aman Deep',
      product_title: 'Classic Oversized Heavyweight Tee',
      rating: 5,
      title: 'Incredible heavyweight drape and fit',
      body: 'The 240 GSM weight is real. Thick ribbed collar does not bacon after wash. Very high quality streetwear silhouette.',
      status: 'approved',
      verified_buyer: true,
      image_url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500',
      created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    },
    {
      id: 'rev-2',
      product_id: productIds.hoodie,
      user_id: 'usr-cust-3',
      customer_name: 'Varun Joshi',
      product_title: 'Essential Pullover Hoodie',
      rating: 5,
      title: 'Custom DTG print came out very crisp',
      body: 'Designed my own artwork in the Bingooo Studio. Colors on fabric matched my monitor very closely. Soft fleece lining.',
      status: 'approved',
      verified_buyer: true,
      image_url: null,
      created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    },
    {
      id: 'rev-3',
      product_id: productIds.graphicTee,
      user_id: 'usr-cust-1',
      customer_name: 'Pooja Sethi',
      product_title: 'Graphic Print Heavyweight Tee',
      rating: 4,
      title: 'Great streetwear cut, runs oversized',
      body: 'Love the graphic print sharpness. It runs oversized as advertised, recommend going true to size for boxy fit.',
      status: 'approved',
      verified_buyer: true,
      image_url: null,
      created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    },
  ] as any[],

  customizations: [
    {
      id: 'cust-101',
      user_id: 'usr-cust-1',
      product_id: productIds.classicTee,
      product_title: 'Classic Oversized Heavyweight Tee',
      status: 'approved',
      print_status: 'ready_to_print',
      design_json: {
        garmentColor: 'Obsidian Black',
        layers: [
          { type: 'text', content: 'BINGOOO STUDIO', fontSize: 32, color: '#FFFFFF', position: { x: 50, y: 35 } },
          { type: 'image', url: '/custom/tshirt-step-3-black.png', position: { x: 50, y: 55 } },
        ],
      },
      preview_url: '/custom/tshirt-step-3-black.png',
      print_spec: {
        method: 'DTG (Direct-to-Garment)',
        placement: 'Back Print (300mm x 420mm)',
        resolutionDPI: 300,
        colorSpace: 'CMYK',
      },
      customer_name: 'Aditi Sharma',
      customer_email: 'customer@bingooo.in',
      created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as any[],

  customization_assets: [] as any[],
  shipments: [] as any[],

  notifications: [
    {
      id: 'notif-1',
      category: 'stock',
      severity: 'critical',
      title: 'Low Stock Alert: Classic Heavyweight Tee (S, Black)',
      description: 'Only 3 units remain in warehouse stock. Low threshold is 5 units.',
      link_href: '/inventory',
      link_text: 'Adjust Stock in Inventory →',
      is_read: false,
      created_at: new Date(Date.now() - 3600000 * 1).toISOString(),
    },
    {
      id: 'notif-2',
      category: 'custom',
      severity: 'warning',
      title: 'New Custom Studio Print Submission (#BING-CUST-9102)',
      description: 'Customer uploaded 300 DPI backprint artwork awaiting DTG production approval.',
      link_href: '/custom-orders',
      link_text: 'Review in Custom Queue →',
      is_read: false,
      created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    },
    {
      id: 'notif-3',
      category: 'order',
      severity: 'info',
      title: 'New High-Value Order Placed (#BING-89421)',
      description: 'Order total of ₹2,498 confirmed via Razorpay UPI.',
      link_href: '/orders',
      link_text: 'View Order →',
      is_read: true,
      created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    },
  ] as any[],

  audit_logs: [
    {
      id: 'log-101',
      admin_email: 'admin@bingooo.in',
      action: 'product.price_update',
      resource: 'products',
      resource_id: productIds.classicTee,
      details: 'Base price updated from ₹1,199 to ₹1,299',
      ip_address: '103.24.12.89',
      created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
    {
      id: 'log-102',
      admin_email: 'siddharth@bingooo.in',
      action: 'order.status_update',
      resource: 'orders',
      resource_id: 'BING-89421',
      details: 'Fulfillment moved to processing with BlueDart AWB# BLUEDART-88219412',
      ip_address: '49.36.18.204',
      created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    },
    {
      id: 'log-103',
      admin_email: 'admin@bingooo.in',
      action: 'payment.captured',
      resource: 'payments',
      resource_id: 'pay-901',
      details: 'Payment of ₹2,498 verified and captured via Razorpay gateway',
      ip_address: '103.24.12.89',
      created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    },
  ] as any[],

  addresses: [
    {
      id: 'addr-1',
      user_id: 'usr-cust-1',
      name: 'Aditi Sharma',
      phone: '9876543210',
      line1: '124, Indiranagar 100ft Road',
      line2: 'Flat 4B, Silicon Heights',
      city: 'Bengaluru',
      state: 'Karnataka',
      postal_code: '560038',
      country: 'IN',
      is_default: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'addr-2',
      user_id: 'usr-cust-1',
      name: 'Aditi Sharma (Work)',
      phone: '9876543210',
      line1: 'Tower B, Bagmane Tech Park',
      line2: 'CV Raman Nagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      postal_code: '560093',
      country: 'IN',
      is_default: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as any[],

  profiles: [
    {
      id: 'usr-cust-1',
      email: 'customer@bingooo.in',
      full_name: 'Aditi Sharma',
      phone: '+91 98765 43210',
      avatar_key: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'usr-admin-1',
      email: 'admin@bingooo.in',
      full_name: 'Mani P.',
      phone: '+91 98765 43210',
      avatar_key: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as any[],

  banners: [
    {
      id: 'ban-1',
      title: 'Wear What Feels Like You',
      subtitle: 'Streetwear silhouettes. Heavyweight 240 GSM combed cotton.',
      ctaText: "Shop Men's Wear",
      targetUrl: '/shop',
      desktopImageUrl: '/hero-banner.png',
      mobileImageUrl: '/hero-banner.png',
      badge: 'DROP 01 • OVERSIZED FIT',
      priority: 1,
      isActive: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'ban-2',
      title: 'Everyday Luxury. Built to Last.',
      subtitle: 'Minimalist cuts crafted from premium combed cotton. Elevated aesthetics.',
      ctaText: 'Explore Drop 02',
      targetUrl: '/shop',
      desktopImageUrl: '/hero-banner-2.jpg',
      mobileImageUrl: '/hero-banner-2.jpg',
      badge: 'STUDIO DROP • ARCHITECTURAL EDIT',
      priority: 2,
      isActive: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'ban-3',
      title: 'Tailored Statement Menswear',
      subtitle: 'Signature back prints, relaxed drape, and confident proportions.',
      ctaText: 'Shop The Look',
      targetUrl: '/shop',
      desktopImageUrl: '/hero-banner-3.jpg',
      mobileImageUrl: '/hero-banner-3.jpg',
      badge: 'CAMPAIGN 2026 • SIGNATURE FIT',
      priority: 3,
      isActive: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'ban-4',
      title: 'Natural Earth Tones & Minimalism',
      subtitle: 'Warm cream streetwear essentials with precision embroidery.',
      ctaText: 'Discover Essentials',
      targetUrl: '/shop',
      desktopImageUrl: '/hero-banner-4.jpg',
      mobileImageUrl: '/hero-banner-4.jpg',
      badge: 'LIMITED EDITION • NATURAL PALETTE',
      priority: 4,
      isActive: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'ban-5',
      title: 'Heavyweight Crimson Collection',
      subtitle: 'Ultra-warm drop-shoulder hoodies with iconic distressed B artwork.',
      ctaText: 'Create Your Design',
      targetUrl: '/customize',
      desktopImageUrl: '/hero-banner-5.jpg',
      mobileImageUrl: '/hero-banner-5.jpg',
      badge: 'CUSTOM STUDIO • HOODIES & TEES',
      priority: 5,
      isActive: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as any[],

  settings: {
    store_name: 'Bingooo Luxury Streetwear',
    store_email: 'care@bingooo.in',
    store_phone: '+91 98765 43210',
    support_hours: 'Mon - Sat: 10:00 AM - 7:00 PM IST',
    cod_enabled: true,
    cod_deposit_percentage: 30,
    shipping_fee_default: 99,
    free_shipping_threshold: 999,
    tax_rate_percentage: 5,
    max_upload_size_mb: 15,
    currency: 'INR',
    return_window_days: 7,
    dtg_print_lead_days: 3,
  } as Record<string, any>,

  media_assets: [
    {
      id: 'asset-1',
      name: 'heavyweight-tee-black-front.jpg',
      category: 'products',
      url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop',
      sizeBytes: 840000,
      dimensions: '1600x2000',
      uploaded_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
    {
      id: 'asset-2',
      name: 'oversized-hoodie-bone-white.jpg',
      category: 'products',
      url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop',
      sizeBytes: 1200000,
      dimensions: '1600x2000',
      uploaded_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    },
    {
      id: 'asset-3',
      name: 'summer-drop-hero-banner-desktop.jpg',
      category: 'banners',
      url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&auto=format&fit=crop',
      sizeBytes: 2450000,
      dimensions: '2880x1200',
      uploaded_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    },
    {
      id: 'asset-4',
      name: 'tokyo-cyber-custom-graphic.png',
      category: 'designs',
      url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop',
      sizeBytes: 650000,
      dimensions: '1200x1200',
      uploaded_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    },
    {
      id: 'asset-5',
      name: 'cargo-pants-styling-lookbook.jpg',
      category: 'lookbook',
      url: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=800&auto=format&fit=crop',
      sizeBytes: 1800000,
      dimensions: '1800x2400',
      uploaded_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    },
  ] as any[],
};
